# Generated by Django 5.0.1 on 2024-01-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizzleslice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Forders.canapecompany.co.nz%2Fchardonnay-1&psig=AOvVaw0PoNZihi8Wnlo7FkNcpVzo&ust=1706346017939000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCKjK8LbY-oMDFQAAAAAdAAAAABAD', max_length=500),
        ),
    ]
