# Generated by Django 5.0.1 on 2024-01-26 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizzleslice', '0004_alter_item_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_intro',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
    ]
