# Generated by Django 5.0.1 on 2024-01-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizzleslice', '0005_item_item_intro_alter_item_item_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_intro',
            field=models.CharField(default='Intro incoming', max_length=200),
        ),
    ]
