# Generated by Django 5.0.1 on 2024-01-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizzleslice', '0006_alter_item_item_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_intro',
            field=models.CharField(max_length=200),
        ),
    ]
